language: c

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq debhelper dpkg-dev cmake libevent-dev libglib2.0-dev libgmime-2.6-dev liblua5.1-0-dev libpcre3-dev cdbs libssl-dev libjudy-dev

script: 
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../_install -DCMAKE_C_COMPILER=$CC
  - cmake --build . --target install

compiler:
  - clang
  - gcc

branches:
  only:
    - master
